version: '3.7'

services:
    app:
        build:
            context: docker/app
        container_name: app
        ports:
            - "8888:80"
        volumes:
            - .:/var/www/html:rw
        depends_on:
            - db
        # networks:
        # - wp-net
    db:
        image: mysql
        container_name: db
        ports:
            - "3307:3306"
        environment:
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_DATABASE: dales_db
        volumes:
            - db-data:/var/lib/mysql
    #   networks:
        # - wp-net
  
#   networks:
    # wp-net:
    #   driver: bridge
  
volumes:
    db-data:
  