DROP TABLE IF EXISTS login;

CREATE TABLE user_login (
    id int AUTO_INCREMENT PRIMARY,
    user_name VARCHAR(255),
    password_hash VARCHAR(255),
    update_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);